import type { Property } from './api';

export const demoProperties: Property[] = [
  {
    _id: 'demo-1',
    title: '5 Marla Luxury House in Bahria Town Lahore',
    slug: '5-marla-luxury-house-bahria-town-lahore',
    purpose: 'sale',
    category: 'house',
    status: 'available',
    isFeatured: true,
    isVerified: true,
    nocApproved: true,
    city: 'Lahore',
    area: 'Bahria Town',
    block: 'Sector E',
    price: 29000000,
    priceLabel: 'Rs. 2.90 Crore',
    size: 5,
    sizeUnit: 'Marla',
    bedrooms: 5,
    bathrooms: 6,
    parking: 1,
    possession: 'Ready for possession',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c'],
    description: 'Verified luxury home in a secure community near schools, parks, mosque, and commercial access.',
    amenities: ['CCTV', 'Parking', 'Backup power', 'Parks nearby'],
    nearby: ['Bahria Hospital', 'Ring Road', 'Food Court'],
    agent: { name: 'Awais Zaheer', phone: '+92 321 1112508', whatsapp: '+923211112508', agency: 'RB Developers' }
  },
  {
    _id: 'demo-2',
    title: 'Commercial Office on Shahrah-e-Faisal Karachi',
    slug: 'commercial-office-shahrah-e-faisal-karachi',
    purpose: 'sale',
    category: 'office',
    status: 'sold',
    isFeatured: true,
    isVerified: true,
    nocApproved: false,
    city: 'Karachi',
    area: 'Shahrah-e-Faisal',
    price: 72360000,
    priceLabel: 'Rs. 45,000 / SqFt',
    size: 1608,
    sizeUnit: 'SqFt',
    bathrooms: 1,
    parking: 2,
    possession: 'Vacant',
    images: ['https://images.unsplash.com/photo-1497366754035-f200968a6e72'],
    description: 'High-demand office space on Karachi’s commercial corridor with strong rental potential.',
    amenities: ['Elevator', 'Security', 'Reception', 'Backup power'],
    nearby: ['Main road', 'Banks', 'Restaurants'],
    agent: { name: 'Faraz Ahmed', phone: '+92 333 1524862', whatsapp: '+923331524862', agency: 'RB Developers' }
  },
  {
    _id: 'demo-3',
    title: 'Off-Plan Apartment with Installments in Murree',
    slug: 'off-plan-apartment-installments-murree',
    purpose: 'off-plan',
    category: 'apartment',
    status: 'available',
    isFeatured: false,
    isVerified: true,
    nocApproved: true,
    city: 'Murree',
    area: 'New Murree Resort',
    price: 12500000,
    priceLabel: 'Rs. 1.25 Crore',
    size: 780,
    sizeUnit: 'SqFt',
    bedrooms: 1,
    bathrooms: 1,
    possession: '2027 expected',
    images: ['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee'],
    description: 'Tourism-led investment apartment with installment plan and managed rental potential.',
    amenities: ['Mountain view', 'Installment plan', 'Rental management', 'Security'],
    nearby: ['Expressway', 'Tourism spots', 'Restaurants'],
    agent: { name: 'Consultant Team', phone: '+92 300 7444006', whatsapp: '+923007444006', agency: 'RB Developers' }
  }
];
